### ISSUE TITLE
consider taking 02packages from www.cpan.org

### ISSUE THREAD

**Issue by haarg** [miyagawa/cpanmetadb-perl#7]
Currently, cpanmetadb appears to be using an 02packages file from cpan.metacpan.org.  cpanm uses www.cpan.org for its mirror by default.  This means if the two mirrors get out of sync, cpanmetadb will report a version that isn't available on the mirror it is using.

While generally www.cpan.org should be kept up to date, there have been issues with this over the last couple days.  Given the possible failures, having the indexing slightly out of date but matching with what is on the default mirror seems like a better balance.

**Comment by miyagawa** [comment]
The problem with `www.cpan.org` used to be that it was a geo redirector to a mirror near the client, so it's unknown whether you have a fast mirror or not. I think it's now on fastly (as well as metacpan cpan mirror is), and it's pointing to one origin.

I understand the issue here, and cpanm actually does have an option `--metacpan`, which checks if the module is "too fresh" and explicitly falls back to the metacpan mirror.

I am curious if we should actually change cpanm's default mirror to metacpan at this point.

**Comment by haarg** [comment]
So now that www.cpan.org is behind fastly, it seems like it shouldn't be a problem for that to be used as the indexing source.

I have no particular opinion about using metacpan's mirror by default.  Although one issue with the current behavior of cpanm is that even if I have it configured to use metacpan's mirror via https in the environment, it will sometimes switch to backpan or metacpan via http.
